# Individual workflow configuration
enabled: true
description: "Single phase execution workflow"
timeout: 300
max_retries: 3

phases:
  - name: "individual_task"
    timeout: 300
    required: true

agents:
  individual:
    model: gpt-4
    temperature: 0.7
    max_tokens: 4000