# TDD workflow configuration
enabled: true
description: "Test-Driven Development workflow"
timeout: 600
max_retries: 3

phases:
  - name: "test_planning"
    timeout: 120
    required: true
  - name: "test_writing"
    timeout: 180
    required: true
  - name: "implementation"
    timeout: 300
    required: true
  - name: "validation"
    timeout: 120
    required: true

agents:
  test_planner:
    model: gpt-4
    temperature: 0.5
    max_tokens: 3000
  test_writer:
    model: gpt-4
    temperature: 0.3
    max_tokens: 4000
  coder:
    model: gpt-4
    temperature: 0.7
    max_tokens: 4000
  validator:
    model: gpt-4
    temperature: 0.2
    max_tokens: 2000

settings:
  coverage_threshold: 80
  enforce_red_green_refactor: true
  mutation_testing: false