"""DocumentWriter service responsible for persisting generated artefacts.

This component is **environment-agnostic**: it only knows how to materialise
files and directories on a local filesystem. The Orchestrator (or another
adapter layer) decides *where* to persist – local FS, S3, Git repo, etc. – and
can swap this implementation accordingly.

The expected input schema matches the CodingAgent (and other agents) output
contract:

```
{
    "files": [
        {"path": "src/utils/math/fractions.py", "content": "...", "binary": false},
        {"path": "assets/logo.png", "content": "<BASE64>", "binary": true}
    ],
    "directories": ["src", "src/utils", "assets/images"],
}
```

• Missing parent directories are created automatically
• File writes are *atomic* where possible (write-then-move)
• Binary files are base64-decoded before writing
• All writes stay confined within `base_dir` (path-traversal protection)
"""
from __future__ import annotations

import base64
import os
from pathlib import Path
from typing import Dict, List, Sequence

from fastapi.logger import logger  # Re-use project logging config

__all__ = ["DocumentWriter", "PersistenceResult", "FileWriteStatus"]


class FileWriteStatus:
    """Result for a single file write operation."""

    def __init__(self, path: str, success: bool, error: str | None = None) -> None:
        self.path = path
        self.success = success
        self.error = error

    def dict(self) -> Dict[str, str | bool | None]:
        return {"path": self.path, "success": self.success, "error": self.error}


class PersistenceResult:
    """Aggregate result of a persistence call."""

    def __init__(self, file_results: Sequence[FileWriteStatus]) -> None:
        self.file_results = list(file_results)

    @property
    def success(self) -> bool:
        return all(r.success for r in self.file_results)

    def dict(self) -> Dict[str, List[Dict[str, str | bool | None]]]:
        return {"files": [r.dict() for r in self.file_results], "success": self.success}


class DocumentWriter:
    """Utility class for persisting files/directories generated by agents."""

    def __init__(self, base_dir: str | Path) -> None:
        self.base_dir = Path(base_dir).resolve()
        self.base_dir.mkdir(parents=True, exist_ok=True)
        logger.info("📄 DocumentWriter initialised at %s", self.base_dir)

    # ---------------------------------------------------------------------
    # Public API
    # ---------------------------------------------------------------------
    def persist(self, payload: Dict) -> PersistenceResult:
        """Persist artefacts described in *payload*.

        Parameters
        ----------
        payload: Dict
            Expected to contain optional keys `files` (list[dict]) and
            `directories` (list[str]).
        """
        dirs: List[str] = list(payload.get("directories", []))
        files: List[Dict] = list(payload.get("files", []))

        # 1. Create directories first
        for directory in dirs:
            self._make_directory(directory)

        # 2. Write each file
        file_results: List[FileWriteStatus] = []
        for file_desc in files:
            result = self._write_file(file_desc)
            file_results.append(result)

        return PersistenceResult(file_results)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _safe_join(self, *parts: str | Path) -> Path:
        """Join *parts* to base_dir while preventing path traversal."""
        candidate = self.base_dir.joinpath(*parts).resolve()
        if self.base_dir not in candidate.parents and candidate != self.base_dir:
            raise ValueError(f"Attempted path traversal with path: {candidate}")
        return candidate

    def _make_directory(self, directory: str | Path) -> None:
        path = self._safe_join(directory)
        path.mkdir(parents=True, exist_ok=True)
        logger.debug("📂 Created directory %s", path.relative_to(self.base_dir))

    def _write_file(self, file_desc: Dict) -> FileWriteStatus:
        path_str: str = str(file_desc.get("path"))
        content = file_desc.get("content", "")
        is_binary = bool(file_desc.get("binary", False))

        if not path_str:
            return FileWriteStatus(path_str, False, "Missing path")

        try:
            path = self._safe_join(path_str)
            # Ensure parent directories exist
            path.parent.mkdir(parents=True, exist_ok=True)

            # Decode binary if needed
            if is_binary:
                data = base64.b64decode(content)
                mode = "wb"
            else:
                data = content
                mode = "wb" if isinstance(content, (bytes, bytearray)) else "w"

            # Write atomically where possible
            tmp_path = path.with_suffix(path.suffix + ".tmp")
            with open(tmp_path, mode) as f:
                if isinstance(data, (bytes, bytearray)):
                    f.write(data)
                else:
                    f.write(str(data))
            tmp_path.replace(path)
            logger.debug("✅ Wrote %s", path.relative_to(self.base_dir))
            return FileWriteStatus(path_str, True)
        except Exception as exc:  # pylint: disable=broad-except
            logger.error("❌ Failed to write %s – %s", path_str, exc)
            return FileWriteStatus(path_str, False, str(exc))
