"""
Workflow state management for LangGraph-based agent orchestration.

This module defines the state schema and related utilities for managing
agent workflow state across the LangGraph StateGraph.
"""

from enum import Enum
from typing import Any, Dict, List, Optional, TypedDict

from pydantic import BaseModel, Field


class WorkflowStatus(str, Enum):
    """Status of the workflow execution."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class AgentType(str, Enum):
    """Types of agents available in the system."""

    SPEC = "spec"
    DESIGN = "design"
    CODING = "coding"
    REVIEW = "review"
    TEST = "test"


class Task(BaseModel):
    """Task model representing a single task extracted from a user request."""

    task_id: str = Field(description="Unique identifier for the task")
    title: str = Field(description="Short descriptive title for the task")
    description: str = Field(
        description="Detailed description of what needs to be done"
    )
    priority: str = Field(description="Priority level (high, medium, low)")
    estimated_hours: float = Field(description="Estimated hours to complete")
    dependencies: List[str] = Field(
        default_factory=list, description="List of task IDs this task depends on"
    )
    assignee: Optional[str] = Field(
        default=None, description="Agent type that should handle this task"
    )
    status: WorkflowStatus = Field(
        default=WorkflowStatus.PENDING, description="Current status of the task"
    )


class AgentResult(BaseModel):
    """Result from an agent execution."""

    agent_type: AgentType
    success: bool
    result: Optional[Any] = None
    error_message: Optional[str] = None
    execution_time: Optional[float] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AgentWorkflowState(TypedDict):
    """
    State schema for the LangGraph workflow.

    This represents the complete state that flows through the agent workflow graph,
    containing all necessary information for agents to process tasks and coordinate.
    """

    # Core workflow information
    workflow_id: str
    task_id: str
    task_type: str
    user_request: str
    current_step: str
    status: WorkflowStatus

    # Agent-specific results
    spec_tasks: List[Dict[str, Any]]  # Tasks generated by SpecAgent
    design_specs: Optional[str]  # Design specifications from DesignAgent
    code_result: Optional[str]  # Code generated by CodingAgent
    review_feedback: Optional[str]  # Feedback from ReviewAgent
    test_results: Optional[str]  # Test results from TestAgent

    # Execution tracking
    completed_agents: List[str]  # List of agents that have completed
    failed_agents: List[str]  # List of agents that failed
    agent_results: List[Dict[str, Any]]  # Detailed results from each agent

    # Error handling
    error_messages: List[str]  # Collection of error messages
    retry_count: int  # Number of retries attempted
    max_retries: int  # Maximum number of retries allowed

    # Metadata and context
    metadata: Dict[str, Any]  # Additional metadata
    created_at: str  # Timestamp when workflow was created
    updated_at: str  # Timestamp when workflow was last updated


def create_initial_state(
    workflow_id: str,
    task_id: str,
    task_type: str,
    user_request: str,
    max_retries: int = 3,
) -> AgentWorkflowState:
    """
    Create an initial workflow state.

    Args:
        workflow_id: Unique identifier for the workflow
        task_id: Unique identifier for the task
        task_type: Type of task to be processed
        user_request: Original user request
        max_retries: Maximum number of retries allowed

    Returns:
        Initial AgentWorkflowState
    """
    from datetime import datetime

    timestamp = datetime.now().isoformat()

    return AgentWorkflowState(
        workflow_id=workflow_id,
        task_id=task_id,
        task_type=task_type,
        user_request=user_request,
        current_step="spec",
        status=WorkflowStatus.PENDING,
        # Agent results (initially empty)
        spec_tasks=[],
        design_specs=None,
        code_result=None,
        review_feedback=None,
        test_results=None,
        # Execution tracking
        completed_agents=[],
        failed_agents=[],
        agent_results=[],
        # Error handling
        error_messages=[],
        retry_count=0,
        max_retries=max_retries,
        # Metadata
        metadata={},
        created_at=timestamp,
        updated_at=timestamp,
    )


def update_state_timestamp(state: AgentWorkflowState) -> AgentWorkflowState:
    """
    Update the timestamp of the workflow state.

    Args:
        state: Current workflow state

    Returns:
        Updated workflow state with new timestamp
    """
    from datetime import datetime

    state["updated_at"] = datetime.now().isoformat()
    return state


def add_agent_result(
    state: AgentWorkflowState,
    agent_type: AgentType,
    success: bool,
    result: Optional[Any] = None,
    error_message: Optional[str] = None,
    execution_time: Optional[float] = None,
    metadata: Optional[Dict[str, Any]] = None,
) -> AgentWorkflowState:
    """
    Add an agent result to the workflow state.

    Args:
        state: Current workflow state
        agent_type: Type of agent that executed
        success: Whether the agent execution was successful
        result: Result data from the agent
        error_message: Error message if execution failed
        execution_time: Time taken for execution
        metadata: Additional metadata

    Returns:
        Updated workflow state
    """
    agent_result = AgentResult(
        agent_type=agent_type,
        success=success,
        result=result,
        error_message=error_message,
        execution_time=execution_time,
        metadata=metadata or {},
    )

    # Add to agent results
    state["agent_results"].append(agent_result.model_dump())

    # Update completion/failure tracking
    agent_name = agent_type.value
    if success:
        if agent_name not in state["completed_agents"]:
            state["completed_agents"].append(agent_name)
    else:
        if agent_name not in state["failed_agents"]:
            state["failed_agents"].append(agent_name)
        if error_message:
            state["error_messages"].append(f"{agent_name}: {error_message}")

    return update_state_timestamp(state)


def should_retry(state: AgentWorkflowState) -> bool:
    """
    Determine if a workflow should be retried based on its current state.

    Args:
        state: Current workflow state

    Returns:
        True if workflow should be retried, False otherwise
    """
    return (
        state["retry_count"] < state["max_retries"]
        and len(state["failed_agents"]) > 0
        and state["status"] != WorkflowStatus.CANCELLED
    )
