apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-blackwell.fullname" . }}-secrets
  labels:
    {{- include "agent-blackwell.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.env.OPENAI_API_KEY | b64enc | quote }}
  PINECONE_API_KEY: {{ .Values.env.PINECONE_API_KEY | b64enc | quote }}
  SLACK_API_KEY: {{ .Values.env.SLACK_API_KEY | b64enc | quote }}
  SLACK_SIGNING_SECRET: {{ .Values.env.SLACK_SIGNING_SECRET | b64enc | quote }}
  SLACK_CLIENT_ID: {{ .Values.env.SLACK_CLIENT_ID | b64enc | quote }}
  SLACK_CLIENT_SECRET: {{ .Values.env.SLACK_CLIENT_SECRET | b64enc | quote }}
